version: 2

defaults: &defaults
  working_directory: ~/project/log4vue
  docker:
    - image: circleci/node:8-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run: npm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - log4vue

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:unit
      # add codecov once it is actually ran
      # - run:
      #    name: report coverage stats for non-PRs
      #    command: |
      #      if [[ -z $CI_PULL_REQUEST ]]; then
      #        ./node_modules/.bin/codecov
      #      fi

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-unit:
          requires:
            - install
      - lint:
          requires:
            - install
